// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	server "github.com/humanbelnik/load-balancer/internal/balancer/server/server"
	mock "github.com/stretchr/testify/mock"
)

// Pool is an autogenerated mock type for the Pool type
type Pool struct {
	mock.Mock
}

// Alive provides a mock function with no fields
func (_m *Pool) Alive() ([]server.Server, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Alive")
	}

	var r0 []server.Server
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]server.Server, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []server.Server); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]server.Server)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPool creates a new instance of Pool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pool {
	mock := &Pool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
